export enum ModelSupports {
  EVERYWHERE = 'EVERYWHERE',
  TOUCHING_BUILDPLATE = 'TOUCHING_BUILDPLATE',
  NONE = 'NONE',
}

export enum ModelSupportsType {
  NONE = 'NONE',
  LINES = 'LINES',
  GRID = 'GRID',
  TRIANGLES = 'TRIANGLES',
  CONCENTRIC = 'CONCENTRIC',
  ZIGZAG = 'ZIGZAG',
  CROSS = 'CROSS',
  GYROID = 'GYROID',
}
